spring:
  application:
    name: moum

  datasource:
    url: jdbc:mysql://db-pfr3l-kr.vpc-pub-cdb.ntruss.com/studydb
    username: study
    password: bitcamp123!@#
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    cache: false

  servlet:
    multipart:
      enabled: true
      location: ${user.home}/upload
      max-request-size: 30MB
      max-file-size: 10MB

mybatis:
  mapper-locations: classpath:mappers/*.xml  # ?? XML ?? ?? ??
  type-aliases-package: moum.project.domain  # ??? ??? ??? ??? ??

logging:
  level:
    org.springframework.security.web: trace
    moum.project: debug
