spring:
  application:
    name: moum

  config:
    import:
      - "file:${user.home}/config/ncp.properties"

# 운영DB로 변경 예정
  datasource:
    url: jdbc:mysql://db-pfr3l-kr.vpc-pub-cdb.ntruss.com/moum
    username: moum
    password: bitcamp123!@#
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  servlet:
    multipart:
      enabled: true
      location: ${user.home}/upload
      max-request-size: 30MB
      max-file-size: 10MB

#  web:
#    resources:
#      static-locations: file:src/main/resources/static/

  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 180000

mybatis:
  mapper-locations:
  type-aliases-package:

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    moum.project: DEBUG

#server:
#  port: 443
#  ssl:
#    enabled: true
#    key-store: /etc/letsencrypt/live/moum.bangdpool.com/keystore.p12
#    key-store-password: ""
#    key-store-type: PKCS12
#    key-alias: moum
#    key-password: ""

server:
  port: 80
